REGISTRATION_URL = '/register'
FOUND_USER_BY_ID_OR_USERNAME_URL = '/found_user'
GET_ALL_USERS_FROM_DB_URL = '/users'
DELETE_USER_URL = '/delete'
AUTHORIZATION_URL = '/login'
REFRESH_TOKEN_URL = '/refresh'
GET_CURRENT_USER_BY_TOKEN_URL = '/current_user'
BAN_USER_URL = '/ban'
UNBAN_USER_URL = '/unban'

ACCESS_TOKEN_EXPIRE_MINUTES = 10
REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 30

PAGINATOR_ITEMS_PER_PAGE = 10
