"""append caterogies

Revision ID: 305331a0e25d
Revises: 4386423bb6dd
Create Date: 2024-08-16 03:31:14.542148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '305331a0e25d'
down_revision: Union[str, None] = '4386423bb6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'baskets', ['id'])
    op.add_column('store', sa.Column('categories_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'store', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'store', type_='unique')
    op.drop_column('store', 'categories_id')
    op.drop_constraint(None, 'baskets', type_='unique')
    op.drop_table('categories')
    # ### end Alembic commands ###
