"""update tables

Revision ID: 89156eee305a
Revises: 305331a0e25d
Create Date: 2024-08-16 03:33:39.576397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89156eee305a'
down_revision: Union[str, None] = '305331a0e25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['id'])
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
