"""Update tables (append necessary indexes)

Revision ID: fe4d31a2689e
Revises: c5c8f47a9f3d
Create Date: 2024-09-18 17:27:06.927560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4d31a2689e'
down_revision: Union[str, None] = 'c5c8f47a9f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_baskets_users_id'), 'baskets', ['users_id'], unique=False)
    op.create_unique_constraint(None, 'baskets', ['id'])
    op.drop_constraint('fk_baskets_users', 'baskets', type_='foreignkey')
    op.drop_constraint('fk_baskets_products', 'baskets', type_='foreignkey')
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_index(op.f('ix_store_categories_id'), 'store', ['categories_id'], unique=False)
    op.create_index(op.f('ix_store_title'), 'store', ['title'], unique=False)
    op.create_unique_constraint(None, 'store', ['id'])
    op.drop_constraint('fk_products_categories', 'store', type_='foreignkey')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_index(op.f('ix_verification_codes_users_id'), 'verification_codes', ['users_id'], unique=False)
    op.create_unique_constraint(None, 'verification_codes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_codes', type_='unique')
    op.drop_index(op.f('ix_verification_codes_users_id'), table_name='verification_codes')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('fk_products_categories', 'store', 'categories', ['categories_id'], ['id'])
    op.drop_constraint(None, 'store', type_='unique')
    op.drop_index(op.f('ix_store_title'), table_name='store')
    op.drop_index(op.f('ix_store_categories_id'), table_name='store')
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_foreign_key('fk_baskets_products', 'baskets', 'store', ['products_id'], ['id'])
    op.create_foreign_key('fk_baskets_users', 'baskets', 'users', ['users_id'], ['id'])
    op.drop_constraint(None, 'baskets', type_='unique')
    op.drop_index(op.f('ix_baskets_users_id'), table_name='baskets')
    # ### end Alembic commands ###
